#!/bin/sh
		
echo "Choose between pizza, burger or pasta"
read FOOD
if [ $FOOD = "Pizza" ]; then
echo "you seem to like pizza shell"
elif [ $FOOD = "Burger" ]; then
echo "you seem to like burger shell"
elif [ $FOOD = "pasta" ]; then
echo "you seem to like pasta shell"
else echo "you seem to not like our menu"
fi